version: '2'

services:
  app:
    image: 'practice:latest'
    build:
      context: .
    expose:
      - 8080
    ports:
    - 8080:8080
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/foobar
      - SPRING_DATASOURCE_USERNAME=aleksandarvujasinovic
      - SPRING_DATASOURCE_PASSWORD=aleksandarvujasinovic
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=foobar
      - POSTGRES_USER=aleksandarvujasinovic
      - POSTGRES_PASSWORD=aleksandarvujasinovic